/**
 * State action identifiers
 *
 * @format
 */

export const SET_ERROR = "SET_ERROR"
export const DELETE_ERROR = "DELETE_ERROR"
export const SET_FAVOURITES = "SET_FAVOURITES"
export const UPDATE_FAVOURITES = "UPDATE_FAVOURITES"
export const SET_SEARCH_STRING = "SET_SEARCH_STRING"
export const DELETE_SEARCH_STRING = "DELETE_SEARCH_STRING"
export const START_LOADING = "START_LOADING"
export const STOP_LOADING = "STOP_LOADING"
export const SET_MOVIES = "SET_MOVIES"
export const DELETE_MOVIES = "DELETE_MOVIES"
export const SET_SELECTED_MOVIE = "SET_SELECTED_MOVIE"
export const DELETE_SELECTED_MOVIE = "DELETE_SELECTED_MOVIE"
export const SET_SUGGESTIONS = "SET_SUGGESTIONS"
export const DELETE_SUGGESTIONS = "DELETE_SUGGESTIONS"
